### ISSUE TITLE
how I can implements with angular 2 or webpack?

### ISSUE THREAD

**Issue by hiepxanh** [livestyle/atom#14]
I'm writing css on angular 2 and it keep refesh browser rapidly but very slow. I want to use livestyle but look like it not work with angular 2. how can I resolve that ?

**Comment by sergeche** [comment]
LiveStyle doesn’t depends on project or build tool you’re using, it updates CSS directly in browser. Make sure you have both Chrome and Atom extension installed and you associated editor-tobrowser files properly

**Comment by hiepxanh** [comment]
thanks, I'm turning off the angular 2 CSS Encapsulation by:
`
import { Component , ViewEncapsulation} from '@angular/core';
@Component({
  selector: 'app-note',
  templateUrl: './note.component.html',
  styleUrls: ['./note.component.css'],
  encapsulation: ViewEncapsulation.None
})
`
and then, I can work with livestyle again, thanks for your answer

**Comment by hiepxanh** [comment]
well, this new update of angular 2 make me have to create livestyle.json for angular-cli project. it work again and don't have to create view Encapsulation
