### ISSUE TITLE
Deprecated selector in `livestyle-atom/styles/widgets.atom-text-editor.less`

### ISSUE THREAD

**Issue by PixelT** [livestyle/atom#19]
In `livestyle-atom/styles/widgets.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow livestyle-widget` => `atom-text-editor.editor livestyle-widget`

* `atom-text-editor::shadow livestyle-widget[position*="top"]` => `atom-text-editor.editor livestyle-widget[position*="top"]`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by omarciovsena** [comment]
It is also available to me after I updated the atom to version 1.13.0

**Comment by mstashev** [comment]
Same

**Comment by pfberberich** [comment]
Has development been abandoned on this project? This issue has been outstanding for ages.

**Comment by sergeche** [comment]
The project is on hold now due low interest from community

**Comment by sergeche** [comment]
Fixed in v0.2.9

**Comment by mstashev** [comment]
Ok. Well thanks for updating it! How do you go about writing these kinds of
plugins?
