### ISSUE TITLE
LESS: livestyle.json does not work?

### ISSUE THREAD

**Issue by nicothin** [livestyle/atom#5]
I create livestyle.json — http://take.ms/S9q68
But I do not work display value of a variable. 
Please tell me what am I doing wrong?

**Comment by sergeche** [comment]
Don’t understand what you mean. Where do expect to see variable value?

**Comment by nicothin** [comment]
@sergeche  I put the cursor on a variable or mixin, but there is no tips: http://take.ms/hDxqi

**Comment by sergeche** [comment]
https://github.com/livestyle/atom#livestyle-analyzer

> LiveStyle Analyzer works for _currently opened file only_: it doesn’t read data from `@import` or global stylesheets yet. But you can help to make it happen! Stay tuned for updates at [@emmetio](https://twitter.com/emmet.io)

**Comment by nicothin** [comment]
it's a pity!

**Comment by sergeche** [comment]
I’m going to start a crowdfunding campaign to support full project scan ;)

**Comment by nicothin** [comment]
@sergeche where to wait for the announcement? blog on the official website has not been updated for a long time.

**Comment by sergeche** [comment]
Twitter account: [@emmetio](https://twitter.com/emmetio)
